In [1]:
# Import our dependencies
import numpy as np
import pandas as pd
from sqlalchemy import create_engine
from config import db_password

In [2]:
# Read in Movies CSV
movies_df = pd.read_csv("Resources/movies.csv")
movies_df

,movie_name,rating,genre,year_release,score,votes,director,writer,star,country,budget,gross,company,runtime
0,The Shining,R,Drama,1980,8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0
1,The Blue Lagoon,R,Adventure,1980,5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0
3,Airplane!,PG,Comedy,1980,7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0
4,Caddyshack,R,Comedy,1980,7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7663,More to Life,NaN,Drama,2020,3.1,18.0,Joseph Ebanks,Joseph Ebanks,Shannon Bond,United States,7000.0,NaN,NaN,90.0
7664,Dream Round,NaN,Comedy,2020,4.7,36.0,Dusty Dukatz,Lisa Huston,Michael Saquella,United States,NaN,NaN,Cactus Blue Entertainment,90.0
7665,Saving Mbango,NaN,Drama,2020,5.7,29.0,Nkanya Nkwai,Lynno Lovert,Onyama Laura,United States,58750.0,NaN,Embi Productions,NaN
7666,It's Just Us,NaN,Drama,2020,NaN,NaN,James Randall,James Randall,Christina Roz,United States,15000.0,NaN,NaN,120.0
7667,Tee em el,NaN,Horror,2020,5.7,7.0,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,South Africa,NaN,NaN,PK 65 Films,102.0

In [3]:
# Check for duplicates in the dataset movies_df
print(f"Duplicate entries: {movies_df['movie_name'].duplicated().sum()}")

Duplicate entries: 156

In [4]:
# Drop duplicates from movies_df
movies_df.drop_duplicates(subset="movie_name", keep=False, inplace=True)
movies_df

,movie_name,rating,genre,year_release,score,votes,director,writer,star,country,budget,gross,company,runtime
0,The Shining,R,Drama,1980,8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0
1,The Blue Lagoon,R,Adventure,1980,5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0
3,Airplane!,PG,Comedy,1980,7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0
4,Caddyshack,R,Comedy,1980,7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7663,More to Life,NaN,Drama,2020,3.1,18.0,Joseph Ebanks,Joseph Ebanks,Shannon Bond,United States,7000.0,NaN,NaN,90.0
7664,Dream Round,NaN,Comedy,2020,4.7,36.0,Dusty Dukatz,Lisa Huston,Michael Saquella,United States,NaN,NaN,Cactus Blue Entertainment,90.0
7665,Saving Mbango,NaN,Drama,2020,5.7,29.0,Nkanya Nkwai,Lynno Lovert,Onyama Laura,United States,58750.0,NaN,Embi Productions,NaN
7666,It's Just Us,NaN,Drama,2020,NaN,NaN,James Randall,James Randall,Christina Roz,United States,15000.0,NaN,NaN,120.0
7667,Tee em el,NaN,Horror,2020,5.7,7.0,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,South Africa,NaN,NaN,PK 65 Films,102.0

In [5]:
# drop rows with Na values in movies_df
movies_df = movies_df.dropna()
movies_df

,movie_name,rating,genre,year_release,score,votes,director,writer,star,country,budget,gross,company,runtime
0,The Shining,R,Drama,1980,8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0
1,The Blue Lagoon,R,Adventure,1980,5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0
3,Airplane!,PG,Comedy,1980,7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0
4,Caddyshack,R,Comedy,1980,7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7648,Bad Boys for Life,R,Action,2020,6.6,140000.0,Adil El Arbi,Peter Craig,Will Smith,United States,90000000.0,426505244.0,Columbia Pictures,124.0
7649,Sonic the Hedgehog,PG,Action,2020,6.5,102000.0,Jeff Fowler,Pat Casey,Ben Schwartz,United States,85000000.0,319715683.0,Paramount Pictures,99.0
7650,Dolittle,PG,Adventure,2020,5.6,53000.0,Stephen Gaghan,Stephen Gaghan,Robert Downey Jr.,United States,175000000.0,245487753.0,Universal Pictures,101.0
7651,The Call of the Wild,PG,Adventure,2020,6.8,42000.0,Chris Sanders,Michael Green,Harrison Ford,Canada,135000000.0,111105497.0,20th Century Studios,100.0
7652,The Eight Hundred,Not Rated,Action,2020,6.8,3700.0,Hu Guan,Hu Guan,Zhi-zhong Huang,China,80000000.0,461421559.0,Beijing Diqi Yinxiang Entertainment,149.0

In [6]:
#reset the index so that it is in order
movies_df = movies_df.reset_index(drop=True)
movies_df.count()

movie_name      5201
rating          5201
genre           5201
year_release    5201
score           5201
votes           5201
director        5201
writer          5201
star            5201
country         5201
budget          5201
gross           5201
company         5201
runtime         5201
dtype: int64

In [7]:
# Read in Top Movies CSV
top_4000_movies_df = pd.read_csv("Resources/top_4000_movies_data.csv", parse_dates=['Release Date'], dayfirst=True)
top_4000_movies_df

,Release Date,Movie Title,Production Budget,Domestic Gross,Worldwide Gross
0,2019-04-23,Avengers: Endgame,400000000,858373000,2797800564
1,2011-05-20,Pirates of the Caribbean: On Stranger Tides,379000000,241071802,1045713802
2,2015-04-22,Avengers: Age of Ultron,365000000,459005868,1395316979
3,2015-12-16,Star Wars Ep. VII: The Force Awakens,306000000,936662225,2064615817
4,2018-04-25,Avengers: Infinity War,300000000,678815482,2044540523
...,...,...,...,...,...
3995,2067-06-13,You Only Live Twice,9500000,43100000,111600000
3996,1988-10-06,Poltergeist III,9500000,14114000,14114000
3997,2016-12-21,Dangal,9500000,12391761,305149461
3998,2010-03-19,The Runaways,9500000,3573673,5278632
3999,2009-10-30,Gentlemen Broncos,9500000,115155,119955

In [8]:
# Check for duplicates in the dataset top_4000_movies_df
print(f"Duplicate entries: {top_4000_movies_df['Movie Title'].duplicated().sum()}")

Duplicate entries: 48

In [9]:
# Drop duplicates from movies_df
top_4000_movies_df.drop_duplicates(subset="Movie Title", keep=False, inplace=True)

In [10]:
# count number of rows
top_4000_movies_df.count()

Release Date         3883
Movie Title          3904
Production Budget    3904
Domestic Gross       3904
Worldwide Gross      3904
dtype: int64

In [11]:
# Check for duplicates in the dataset top_4000_movies_df
print(f"Duplicate entries: {top_4000_movies_df['Movie Title'].duplicated().sum()}")

Duplicate entries: 0

In [12]:
# drop rows with Na values
top_4000_movies_df = top_4000_movies_df.dropna()

In [13]:
# rename columns for 
top_4000_movies_df.rename(columns={'Release Date':'Release_Date', 'Movie Title':'Movie_Title', 'Production Budget':'Production_Budget', 'Domestic Gross':'Domestic_Gross',
       'Worldwide Gross':'Worldwide_Gross'},inplace=True)

C:\Users\dtj13\anaconda3\envs\PythonData\lib\site-packages\pandas\core\frame.py:4449: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [14]:
# reset the index so that it is in order
top_4000_movies_df.reset_index(drop=True)

,Release_Date,Movie_Title,Production_Budget,Domestic_Gross,Worldwide_Gross
0,2019-04-23,Avengers: Endgame,400000000,858373000,2797800564
1,2011-05-20,Pirates of the Caribbean: On Stranger Tides,379000000,241071802,1045713802
2,2015-04-22,Avengers: Age of Ultron,365000000,459005868,1395316979
3,2015-12-16,Star Wars Ep. VII: The Force Awakens,306000000,936662225,2064615817
4,2018-04-25,Avengers: Infinity War,300000000,678815482,2044540523
...,...,...,...,...,...
3878,2067-06-13,You Only Live Twice,9500000,43100000,111600000
3879,1988-10-06,Poltergeist III,9500000,14114000,14114000
3880,2016-12-21,Dangal,9500000,12391761,305149461
3881,2010-03-19,The Runaways,9500000,3573673,5278632
3882,2009-10-30,Gentlemen Broncos,9500000,115155,119955

In [15]:
# count the number of rows
top_4000_movies_df.count()

Release_Date         3883
Movie_Title          3883
Production_Budget    3883
Domestic_Gross       3883
Worldwide_Gross      3883
dtype: int64

In [16]:
# create string to access postgreSQL database
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/movie_final"

In [17]:
# create engine for sqalchemy
engine = create_engine(db_string)

In [18]:
# export movies_df to movies table
movies_df.to_sql(name='movies', con=engine, index=False)

In [19]:
# export top_4000_movies_df
top_4000_movies_df.to_sql(name='top_4000_movies', con=engine, index=False)

In [20]:
# read in merged_movie_df from pgAdmin and postgreSQL
merged_movies_df = pd.read_sql_query('''SELECT * FROM merged_movies;''', engine)
merged_movies_df

,movie_name,rating,genre,year_release,score,votes,director,writer,star,country,budget,gross,company,runtime,Release_Date,Production_Budget,Domestic_Gross,Worldwide_Gross
0,Avengers: Endgame,PG-13,Action,2019,8.4,903000.0,Anthony Russo,Christopher Markus,Robert Downey Jr.,United States,356000000.0,2.797501e+09,Marvel Studios,181.0,2019-04-23,400000000.0,858373000.0,2.797801e+09
1,Avengers: Age of Ultron,PG-13,Action,2015,7.3,777000.0,Joss Whedon,Joss Whedon,Robert Downey Jr.,United States,250000000.0,1.402810e+09,Marvel Studios,141.0,2015-04-22,365000000.0,459005868.0,1.395317e+09
2,Avengers: Infinity War,PG-13,Action,2018,8.4,897000.0,Anthony Russo,Christopher Markus,Robert Downey Jr.,United States,321000000.0,2.048360e+09,Marvel Studios,149.0,2018-04-25,300000000.0,678815482.0,2.044541e+09
3,Justice League,PG-13,Action,2017,6.1,418000.0,Zack Snyder,Jerry Siegel,Ben Affleck,United States,300000000.0,6.579270e+08,Warner Bros.,120.0,2017-11-13,300000000.0,229024295.0,6.559452e+08
4,Spectre,PG-13,Action,2015,6.8,393000.0,Sam Mendes,John Logan,Daniel Craig,United Kingdom,245000000.0,8.806815e+08,B24,148.0,2015-06-10,300000000.0,200074175.0,8.795008e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5196,The Grey Zone,R,Drama,2001,7.0,10000.0,Tim Blake Nelson,Miklos Nyiszli,David Arquette,United States,5000000.0,6.215920e+05,Killer Films,108.0,NaT,NaN,NaN,NaN
5197,Boyz n the Hood,R,Crime,1991,7.8,130000.0,John Singleton,John Singleton,Cuba Gooding Jr.,United States,6500000.0,5.752907e+07,Columbia Pictures,112.0,NaT,NaN,NaN,NaN
5198,Once Upon a Time... In Hollywood,R,Comedy,2019,7.6,603000.0,Quentin Tarantino,Quentin Tarantino,Leonardo DiCaprio,United States,90000000.0,3.745658e+08,Columbia Pictures,161.0,NaT,NaN,NaN,NaN
5199,House Party 2,R,Comedy,1991,5.3,6100.0,George Jackson,Reginald Hudlin,Christopher Reid,United States,5000000.0,1.943864e+07,"Jackson/McHenry Company,The",94.0,NaT,NaN,NaN,NaN
5200,Naked Lunch,R,Drama,1991,7.0,48000.0,David Cronenberg,William S. Burroughs,Peter Weller,Canada,16000000.0,2.641357e+06,Recorded Picture Company (RPC),115.0,NaT,NaN,NaN,NaN

In [25]:
# drop the Release_Date and country columns
merged_movies_df = merged_movies_df.drop(['Release_Date', 'country'], axis=1)
merged_movies_df.head()

,movie_name,rating,genre,year_release,score,votes,director,writer,star,budget,gross,company,runtime,Production_Budget,Domestic_Gross,Worldwide_Gross
0,Avengers: Endgame,PG-13,Action,2019,8.4,903000.0,Anthony Russo,Christopher Markus,Robert Downey Jr.,356000000.0,2.797501e+09,Marvel Studios,181.0,400000000.0,858373000.0,2.797801e+09
1,Avengers: Age of Ultron,PG-13,Action,2015,7.3,777000.0,Joss Whedon,Joss Whedon,Robert Downey Jr.,250000000.0,1.402810e+09,Marvel Studios,141.0,365000000.0,459005868.0,1.395317e+09
2,Avengers: Infinity War,PG-13,Action,2018,8.4,897000.0,Anthony Russo,Christopher Markus,Robert Downey Jr.,321000000.0,2.048360e+09,Marvel Studios,149.0,300000000.0,678815482.0,2.044541e+09
3,Justice League,PG-13,Action,2017,6.1,418000.0,Zack Snyder,Jerry Siegel,Ben Affleck,300000000.0,6.579270e+08,Warner Bros.,120.0,300000000.0,229024295.0,6.559452e+08
4,Spectre,PG-13,Action,2015,6.8,393000.0,Sam Mendes,John Logan,Daniel Craig,245000000.0,8.806815e+08,B24,148.0,300000000.0,200074175.0,8.795008e+08

In [28]:
# drop duplicate title names
merged_movies_df = merged_movies_df.drop_duplicates(subset= 'movie_name', keep= 'first', inplace=False)
merged_movies_df

,movie_name,rating,genre,year_release,score,votes,director,writer,star,budget,gross,company,runtime,Production_Budget,Domestic_Gross,Worldwide_Gross
0,Avengers: Endgame,PG-13,Action,2019,8.4,903000.0,Anthony Russo,Christopher Markus,Robert Downey Jr.,356000000.0,2.797501e+09,Marvel Studios,181.0,400000000.0,858373000.0,2.797801e+09
1,Avengers: Age of Ultron,PG-13,Action,2015,7.3,777000.0,Joss Whedon,Joss Whedon,Robert Downey Jr.,250000000.0,1.402810e+09,Marvel Studios,141.0,365000000.0,459005868.0,1.395317e+09
2,Avengers: Infinity War,PG-13,Action,2018,8.4,897000.0,Anthony Russo,Christopher Markus,Robert Downey Jr.,321000000.0,2.048360e+09,Marvel Studios,149.0,300000000.0,678815482.0,2.044541e+09
3,Justice League,PG-13,Action,2017,6.1,418000.0,Zack Snyder,Jerry Siegel,Ben Affleck,300000000.0,6.579270e+08,Warner Bros.,120.0,300000000.0,229024295.0,6.559452e+08
4,Spectre,PG-13,Action,2015,6.8,393000.0,Sam Mendes,John Logan,Daniel Craig,245000000.0,8.806815e+08,B24,148.0,300000000.0,200074175.0,8.795008e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5196,The Grey Zone,R,Drama,2001,7.0,10000.0,Tim Blake Nelson,Miklos Nyiszli,David Arquette,5000000.0,6.215920e+05,Killer Films,108.0,NaN,NaN,NaN
5197,Boyz n the Hood,R,Crime,1991,7.8,130000.0,John Singleton,John Singleton,Cuba Gooding Jr.,6500000.0,5.752907e+07,Columbia Pictures,112.0,NaN,NaN,NaN
5198,Once Upon a Time... In Hollywood,R,Comedy,2019,7.6,603000.0,Quentin Tarantino,Quentin Tarantino,Leonardo DiCaprio,90000000.0,3.745658e+08,Columbia Pictures,161.0,NaN,NaN,NaN
5199,House Party 2,R,Comedy,1991,5.3,6100.0,George Jackson,Reginald Hudlin,Christopher Reid,5000000.0,1.943864e+07,"Jackson/McHenry Company,The",94.0,NaN,NaN,NaN
5200,Naked Lunch,R,Drama,1991,7.0,48000.0,David Cronenberg,William S. Burroughs,Peter Weller,16000000.0,2.641357e+06,Recorded Picture Company (RPC),115.0,NaN,NaN,NaN

In [29]:
# drop rows with na values
merged_movies_df = merged_movies_df.dropna()
merged_movies_df

,movie_name,rating,genre,year_release,score,votes,director,writer,star,budget,gross,company,runtime,Production_Budget,Domestic_Gross,Worldwide_Gross
0,Avengers: Endgame,PG-13,Action,2019,8.4,903000.0,Anthony Russo,Christopher Markus,Robert Downey Jr.,356000000.0,2.797501e+09,Marvel Studios,181.0,400000000.0,858373000.0,2.797801e+09
1,Avengers: Age of Ultron,PG-13,Action,2015,7.3,777000.0,Joss Whedon,Joss Whedon,Robert Downey Jr.,250000000.0,1.402810e+09,Marvel Studios,141.0,365000000.0,459005868.0,1.395317e+09
2,Avengers: Infinity War,PG-13,Action,2018,8.4,897000.0,Anthony Russo,Christopher Markus,Robert Downey Jr.,321000000.0,2.048360e+09,Marvel Studios,149.0,300000000.0,678815482.0,2.044541e+09
3,Justice League,PG-13,Action,2017,6.1,418000.0,Zack Snyder,Jerry Siegel,Ben Affleck,300000000.0,6.579270e+08,Warner Bros.,120.0,300000000.0,229024295.0,6.559452e+08
4,Spectre,PG-13,Action,2015,6.8,393000.0,Sam Mendes,John Logan,Daniel Craig,245000000.0,8.806815e+08,B24,148.0,300000000.0,200074175.0,8.795008e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2720,The Lost City,R,Drama,2005,6.6,9300.0,Andy Garcia,Guillermo Cabrera Infante,Andy Garcia,9600000.0,4.408011e+06,Crescent Drive Pictures,144.0,9600000.0,2484186.0,5.256839e+06
2721,Next Friday,R,Comedy,2000,6.2,38000.0,Steve Carr,Ice Cube,Ice Cube,11000000.0,5.982733e+07,New Line Cinema,98.0,9500000.0,57176582.0,5.967531e+07
2722,Poltergeist III,PG,Horror,1988,4.7,17000.0,Gary Sherman,Gary Sherman,Heather O'Rourke,10500000.0,1.411449e+07,Metro-Goldwyn-Mayer (MGM),98.0,9500000.0,14114000.0,1.411400e+07
2723,The Runaways,R,Biography,2010,6.5,47000.0,Floria Sigismondi,Floria Sigismondi,Kristen Stewart,10000000.0,4.681651e+06,River Road Entertainment,106.0,9500000.0,3573673.0,5.278632e+06
2724,Gentlemen Broncos,PG-13,Adventure,2009,6.2,11000.0,Jared Hess,Jared Hess,Michael Angarano,10000000.0,1.184920e+05,Bronco Productions,90.0,9500000.0,115155.0,1.199550e+05